### ISSUE TITLE
code 1 (0x00000001)]

### ISSUE THREAD

**Issue by Vladimir-Human** [resonance-rest/fps#1]
"[The process finished with code 1 (0x00000001)]
Now you can close this terminal using the CTRL+D key. Or press any key to continue..."

![image](https://github.com/whosneksio/wuwa.fps/assets/39053957/0a97a337-c001-42dd-abea-6d1a6106cf61)

**Comment by Vladimir-Human** [comment]
> "[The process finished with code 1 (0x00000001)] Now you can close this terminal using the CTRL+D key. Or press any key to continue..."
> 
> ![image](https://private-user-images.githubusercontent.com/39053957/333270797-0a97a337-c001-42dd-abea-6d1a6106cf61.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0ODI1MDEsIm5iZiI6MTcxNjQ4MjIwMSwicGF0aCI6Ii8zOTA1Mzk1Ny8zMzMyNzA3OTctMGE5N2EzMzctYzAwMS00MmRkLWFiZWEtNmQxYTYxMDZjZjYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIzVDE2MzY0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzN2FjMWFmZjk2MjlmZTY2NWJkZjIwYjdlZDY1MTQ0ZGIxMTEwY2ExNzQ4NzE2ZDk2M2UxMzhkNGM5MmNkMWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9RpFf1MpZsJORWfTnYsSKMsgAFp9x2_dcFz0ZzntGjE)

I believe this is because my game is located in a different place on the disk. You should make it so that we can choose where to install the patch.

**Comment by whosneksio** [comment]
yeah, ill add this soon, i see that u didnt provide the path for the localstorage.db?

**Comment by whosneksio** [comment]
"fixed", check this out https://github.com/whosneksio/wuwa.fps/releases/tag/v0.1.2

**Comment by Vladimir-Human** [comment]
> "fixed", check this out https://github.com/whosneksio/wuwa.fps/releases/tag/v0.1.2

Everything works now, thank you!
